### ISSUE TITLE
ERROR: tools/quilt failed to build.

### ISSUE THREAD

**Issue by jelly27th** [gl-inet/gl-infra-builder#63]
编译使用机型：MT3000
编译环境：wsl2
编译命令：
```
git clone https://github.com/gl-inet/gl-infra-builder.git && cd gl-infra-builder
python3 setup.py -c configs/config-22.03.2.yml
cd openwrt-22.03/openwrt-22.03.2/
 ./scripts/gen_config.py target_mt7981_gl-mt3000 custom_mt3000
 make V=s -j9
```
其中custom_mt3000.yml内容为
```
---
description: Custom packages for GL.inet MT3000
feeds:
  - name: OpenClash
    path: ../feeds_dir/OpenClash
    uri: https://github.com/vernesong/OpenClash.git
    branch: master 

packages:
  - luci
  - luci-base
  - dnsmasq-full
  - coreutils
  - coreutils-nohup
  - bash
  - curl
  - ca-certificates
  - ipset
  - ip-full
  - libcap
  - libcap-bin
  - ruby
  - ruby-yaml
  - unzip
  - iptables
  - kmod-ipt-nat
  - iptables-mod-tproxy
  - iptables-mod-extra
  - kmod-tun
  - luci-compat
  - ip6tables-mod-nat
  - kmod-inet-diag
  - kmod-nft-tproxy
```
错误信息：
```
/usr/bin/pod2man bin/guards > doc/guards.1
make[4]: *** No rule to make target 'compat/column.in', needed by 'po/quilt.pot'.  Stop.
make[4]: Leaving directory '/mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2/build_dir/host/quilt-0.67'
make[3]: *** [Makefile:37: /mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2/build_dir/host/quilt-0.67/.built] Error 2       
make[3]: Leaving directory '/mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2/tools/quilt'
time: tools/quilt/compile#2.44#172.24#62.54
    ERROR: tools/quilt failed to build.
make[2]: *** [tools/Makefile:168: tools/quilt/compile] Error 1
make[2]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2/tools/mkimage'
time: tools/mkimage/compile#0.82#36.89#186.34
make[2]: Leaving directory '/mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2'
make[1]: *** [tools/Makefile:164: /mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2/staging_dir/host/stamp/.tools_compile_yyyyyynnyyyyynyyyyyynyynnyynyyyyyyyyyyyyyyyyyyynynyyyyyyyy] Error 2
make[1]: Leaving directory '/mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2'
make: *** [/mnt/c/Users/Dong/Desktop/Complier/gl-infra-builder/openwrt-22.03/openwrt-22.03.2/include/toplevel.mk:230: world] Error 2
```
不清楚怎么避免这个error，试过编译前用删除`../dl`下的quilt包重新编译，依旧得到相同的error。
